package iso3166

type ISOEntry struct {
	enName       string
	frName       string
	alph2        string
	alph3        string
	numCode      string
	official     bool
	active       bool
	organisation string
	description  string
}

var (
	isocodes = map[string]ISOEntry{
		"AF": {
			enName:       "Afghanistan",
			frName:       "Afghanistan (l')",
			alph2:        "AF",
			alph3:        "AFG",
			numCode:      "004",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AL": {
			enName:       "Albania",
			frName:       "Albanie (l')",
			alph2:        "AL",
			alph3:        "ALB",
			numCode:      "008",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"DZ": {
			enName:       "Algeria",
			frName:       "Algérie (l')",
			alph2:        "DZ",
			alph3:        "DZA",
			numCode:      "012",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AS": {
			enName:       "American Samoa",
			frName:       "Samoa américaines (les)",
			alph2:        "AS",
			alph3:        "ASM",
			numCode:      "016",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AD": {
			enName:       "Andorra",
			frName:       "Andorre (l')",
			alph2:        "AD",
			alph3:        "AND",
			numCode:      "020",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AO": {
			enName:       "Angola",
			frName:       "Angola (l')",
			alph2:        "AO",
			alph3:        "AGO",
			numCode:      "024",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AI": {
			enName:       "Anguilla",
			frName:       "Anguilla",
			alph2:        "AI",
			alph3:        "AIA",
			numCode:      "660",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AQ": {
			enName:       "Antarctica",
			frName:       "Antarctique (l')",
			alph2:        "AQ",
			alph3:        "ATA",
			numCode:      "010",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AG": {
			enName:       "Antigua and Barbuda",
			frName:       "Antigua-et-Barbuda",
			alph2:        "AG",
			alph3:        "ATG",
			numCode:      "028",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AR": {
			enName:       "Argentina",
			frName:       "Argentine (l')",
			alph2:        "AR",
			alph3:        "ARG",
			numCode:      "032",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AM": {
			enName:       "Armenia",
			frName:       "Arménie (l')",
			alph2:        "AM",
			alph3:        "ARM",
			numCode:      "051",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AW": {
			enName:       "Aruba",
			frName:       "Aruba",
			alph2:        "AW",
			alph3:        "ABW",
			numCode:      "533",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AU": {
			enName:       "Australia",
			frName:       "Australie (l')",
			alph2:        "AU",
			alph3:        "AUS",
			numCode:      "036",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AT": {
			enName:       "Austria",
			frName:       "Autriche (l')",
			alph2:        "AT",
			alph3:        "AUT",
			numCode:      "040",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AZ": {
			enName:       "Azerbaijan",
			frName:       "Azerbaïdjan (l')",
			alph2:        "AZ",
			alph3:        "AZE",
			numCode:      "031",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BS": {
			enName:       "Bahamas (the)",
			frName:       "Bahamas (les)",
			alph2:        "BS",
			alph3:        "BHS",
			numCode:      "044",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BH": {
			enName:       "Bahrain",
			frName:       "Bahreïn",
			alph2:        "BH",
			alph3:        "BHR",
			numCode:      "048",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BD": {
			enName:       "Bangladesh",
			frName:       "Bangladesh (le)",
			alph2:        "BD",
			alph3:        "BGD",
			numCode:      "050",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BB": {
			enName:       "Barbados",
			frName:       "Barbade (la)",
			alph2:        "BB",
			alph3:        "BRB",
			numCode:      "052",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BY": {
			enName:       "Belarus",
			frName:       "Bélarus (le)",
			alph2:        "BY",
			alph3:        "BLR",
			numCode:      "112",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BE": {
			enName:       "Belgium",
			frName:       "Belgique (la)",
			alph2:        "BE",
			alph3:        "BEL",
			numCode:      "056",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BZ": {
			enName:       "Belize",
			frName:       "Belize (le)",
			alph2:        "BZ",
			alph3:        "BLZ",
			numCode:      "084",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BJ": {
			enName:       "Benin",
			frName:       "Bénin (le)",
			alph2:        "BJ",
			alph3:        "BEN",
			numCode:      "204",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BM": {
			enName:       "Bermuda",
			frName:       "Bermudes (les)",
			alph2:        "BM",
			alph3:        "BMU",
			numCode:      "060",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AX": {
			enName:       "Åland Islands", // U+00C5
			frName:       "Åland(les Îles)",
			alph2:        "AX",
			alph3:        "ALA",
			numCode:      "248",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BT": {
			enName:       "Bhutan",
			frName:       "Bhoutan (le)",
			alph2:        "BT",
			alph3:        "BTN",
			numCode:      "064",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BO": {
			enName:       "Bolivia (Plurinational State of)",
			frName:       "Bolivie (État plurinational de)",
			alph2:        "BO",
			alph3:        "BOL",
			numCode:      "068",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BQ": {
			enName:       "Bonaire, Sint Eustatius and Saba",
			frName:       "Bonaire, Saint-Eustache et Saba",
			alph2:        "BQ",
			alph3:        "BES",
			numCode:      "535",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BA": {
			enName:       "Bosnia and Herzegovina",
			frName:       "Bosnie-Herzégovine (la)",
			alph2:        "BA",
			alph3:        "BIH",
			numCode:      "070",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BW": {
			enName:       "Botswana",
			frName:       "Botswana (le)",
			alph2:        "BW",
			alph3:        "BWA",
			numCode:      "072",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BV": {
			enName:       "Bouvet Island",
			frName:       "Bouvet (l'Île)",
			alph2:        "BV",
			alph3:        "BVT",
			numCode:      "074",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BR": {
			enName:       "Brazil",
			frName:       "Brésil (le)",
			alph2:        "BR",
			alph3:        "BRA",
			numCode:      "076",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"IO": {
			enName:       "British Indian Ocean Territory (the)",
			frName:       "Indien (le Territoire britannique de l'océan)",
			alph2:        "IO",
			alph3:        "IOT",
			numCode:      "086",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BN": {
			enName:       "Brunei Darussalam",
			frName:       "Brunéi Darussalam (le)",
			alph2:        "BN",
			alph3:        "BRN",
			numCode:      "096",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BG": {
			enName:       "Bulgaria",
			frName:       "Bulgarie (la)",
			alph2:        "BG",
			alph3:        "BGR",
			numCode:      "100",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BF": {
			enName:       "Burkina Faso",
			frName:       "Burkina Faso (le)",
			alph2:        "BF",
			alph3:        "BFA",
			numCode:      "854",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BI": {
			enName:       "Burundi",
			frName:       "Burundi (le)",
			alph2:        "BI",
			alph3:        "BDI",
			numCode:      "108",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CV": {
			enName:       "Cabo Verde",
			frName:       "Cabo Verde",
			alph2:        "CV",
			alph3:        "CPV",
			numCode:      "132",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"KH": {
			enName:       "Cambodia",
			frName:       "Cambodge (le)",
			alph2:        "KH",
			alph3:        "KHM",
			numCode:      "116",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CM": {
			enName:       "Cameroon",
			frName:       "Cameroun (le)",
			alph2:        "CM",
			alph3:        "CMR",
			numCode:      "120",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CA": {
			enName:       "Canada",
			frName:       "Canada (le)",
			alph2:        "CA",
			alph3:        "CAN",
			numCode:      "124",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"KY": {
			enName:       "Cayman Islands (the)",
			frName:       "Caïmans (les Îles)",
			alph2:        "KY",
			alph3:        "CYM",
			numCode:      "136",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CF": {
			enName:       "Central African Republic (the)",
			frName:       "République centrafricaine (la)",
			alph2:        "CF",
			alph3:        "CAF",
			numCode:      "140",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TD": {
			enName:       "Chad",
			frName:       "Tchad (le)",
			alph2:        "TD",
			alph3:        "TCD",
			numCode:      "148",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CL": {
			enName:       "Chile",
			frName:       "Chili (le)",
			alph2:        "CL",
			alph3:        "CHL",
			numCode:      "152",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CN": {
			enName:       "China",
			frName:       "Chine (la)",
			alph2:        "CN",
			alph3:        "CHN",
			numCode:      "156",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CX": {
			enName:       "Christmas Island",
			frName:       "Christmas (l'Île)",
			alph2:        "CX",
			alph3:        "CXR",
			numCode:      "162",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CC": {
			enName:       "Cocos (Keeling) Islands (the)",
			frName:       "Cocos (les Îles)/ Keeling (les Îles)",
			alph2:        "CC",
			alph3:        "CCK",
			numCode:      "166",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CO": {
			enName:       "Colombia",
			frName:       "Colombie (la)",
			alph2:        "CO",
			alph3:        "COL",
			numCode:      "170",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"KM": {
			enName:       "Comoros (the)",
			frName:       "Comores (les)",
			alph2:        "KM",
			alph3:        "COM",
			numCode:      "174",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CD": {
			enName:       "Congo (the Democratic Republic of the)",
			frName:       "Congo (la République démocratique du)",
			alph2:        "CD",
			alph3:        "COD",
			numCode:      "180",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CG": {
			enName:       "Congo (the)",
			frName:       "Congo (le)",
			alph2:        "CG",
			alph3:        "COG",
			numCode:      "178",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CK": {
			enName:       "Cook Islands (the)",
			frName:       "Cook (les Îles)",
			alph2:        "CK",
			alph3:        "COK",
			numCode:      "184",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CR": {
			enName:       "Costa Rica",
			frName:       "Costa Rica (le)",
			alph2:        "CR",
			alph3:        "CRI",
			numCode:      "188",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"HR": {
			enName:       "Croatia",
			frName:       "Croatie (la)",
			alph2:        "HR",
			alph3:        "HRV",
			numCode:      "191",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CU": {
			enName:       "Cuba",
			frName:       "Cuba",
			alph2:        "CU",
			alph3:        "CUB",
			numCode:      "192",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CW": {
			enName:       "Curaçao",
			frName:       "Curaçao",
			alph2:        "CW",
			alph3:        "CUW",
			numCode:      "531",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CY": {
			enName:       "Cyprus",
			frName:       "Chypre",
			alph2:        "CY",
			alph3:        "CYP",
			numCode:      "196",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CZ": {
			enName:       "Czechia",
			frName:       "Tchéquie (la)",
			alph2:        "CZ",
			alph3:        "CZE",
			numCode:      "203",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CI": {
			enName:       "Côte d'Ivoire",
			frName:       "Côte d'Ivoire (la)",
			alph2:        "CI",
			alph3:        "CIV",
			numCode:      "384",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"DK": {
			enName:       "Denmark",
			frName:       "Danemark (le)",
			alph2:        "DK",
			alph3:        "DNK",
			numCode:      "208",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"DJ": {
			enName:       "Djibouti",
			frName:       "Djibouti",
			alph2:        "DJ",
			alph3:        "DJI",
			numCode:      "262",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"DM": {
			enName:       "Dominica",
			frName:       "Dominique (la)",
			alph2:        "DM",
			alph3:        "DMA",
			numCode:      "212",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"DO": {
			enName:       "Dominican Republic (the)",
			frName:       "dominicaine (la République)",
			alph2:        "DO",
			alph3:        "DOM",
			numCode:      "214",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"EC": {
			enName:       "Ecuador",
			frName:       "Équateur (l')",
			alph2:        "EC",
			alph3:        "ECU",
			numCode:      "218",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"EG": {
			enName:       "Egypt",
			frName:       "Égypte (l')",
			alph2:        "EG",
			alph3:        "EGY",
			numCode:      "818",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SV": {
			enName:       "El Salvador",
			frName:       "El Salvador",
			alph2:        "SV",
			alph3:        "SLV",
			numCode:      "222",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GQ": {
			enName:       "Equatorial Guinea",
			frName:       "Guinée équatoriale (la)",
			alph2:        "GQ",
			alph3:        "GNQ",
			numCode:      "226",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"ER": {
			enName:       "Eritrea",
			frName:       "Érythrée (l')",
			alph2:        "ER",
			alph3:        "ERI",
			numCode:      "232",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"EE": {
			enName:       "Estonia",
			frName:       "Estonie (l')",
			alph2:        "EE",
			alph3:        "EST",
			numCode:      "233",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SZ": {
			enName:       "Eswatini",
			frName:       "Eswatini (l')",
			alph2:        "SZ",
			alph3:        "SWZ",
			numCode:      "748",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"ET": {
			enName:       "Ethiopia",
			frName:       "Éthiopie (l')",
			alph2:        "ET",
			alph3:        "ETH",
			numCode:      "231",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"FK": {
			enName:       "Falkland Islands (the) [Malvinas]",
			frName:       "Falkland (les Îles)/Malouines (les Îles)",
			alph2:        "FK",
			alph3:        "FLK",
			numCode:      "238",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"FO": {
			enName:       "Faroe Islands (the)",
			frName:       "Féroé (les Îles)",
			alph2:        "FO",
			alph3:        "FRO",
			numCode:      "234",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"FJ": {
			enName:       "Fiji",
			frName:       "Fidji (les)",
			alph2:        "FJ",
			alph3:        "FJI",
			numCode:      "242",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"FI": {
			enName:       "Finland",
			frName:       "Finlande (la)",
			alph2:        "FI",
			alph3:        "FIN",
			numCode:      "246",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"FR": {
			enName:       "France",
			frName:       "France (la)",
			alph2:        "FR",
			alph3:        "FRA",
			numCode:      "250",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GF": {
			enName:       "French Guiana",
			frName:       "Guyane française (la )",
			alph2:        "GF",
			alph3:        "GUF",
			numCode:      "254",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PF": {
			enName:       "French Polynesia",
			frName:       "Polynésie française (la)",
			alph2:        "PF",
			alph3:        "PYF",
			numCode:      "258",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TF": {
			enName:       "French Southern Territories (the)",
			frName:       "Terres australes françaises (les)",
			alph2:        "TF",
			alph3:        "ATF",
			numCode:      "260",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GA": {
			enName:       "Gabon",
			frName:       "Gabon (le)",
			alph2:        "GA",
			alph3:        "GAB",
			numCode:      "266",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GM": {
			enName:       "Gambia (the)",
			frName:       "Gambie (la)",
			alph2:        "GM",
			alph3:        "GMB",
			numCode:      "270",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GE": {
			enName:       "Georgia",
			frName:       "Géorgie (la)",
			alph2:        "GE",
			alph3:        "GEO",
			numCode:      "268",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"DE": {
			enName:       "Germany",
			frName:       "Allemagne (l')",
			alph2:        "DE",
			alph3:        "DEU",
			numCode:      "276",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GH": {
			enName:       "Ghana",
			frName:       "Ghana (le)",
			alph2:        "GH",
			alph3:        "GHA",
			numCode:      "288",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GI": {
			enName:       "Gibraltar",
			frName:       "Gibraltar",
			alph2:        "GI",
			alph3:        "GIB",
			numCode:      "292",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GR": {
			enName:       "Greece",
			frName:       "Grèce (la)",
			alph2:        "GR",
			alph3:        "GRC",
			numCode:      "300",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GL": {
			enName:       "Greenland",
			frName:       "Groenland (le)",
			alph2:        "GL",
			alph3:        "GRL",
			numCode:      "304",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GD": {
			enName:       "Grenada",
			frName:       "Grenade (la)",
			alph2:        "GD",
			alph3:        "GRD",
			numCode:      "308",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GP": {
			enName:       "Guadeloupe",
			frName:       "Guadeloupe (la)",
			alph2:        "GP",
			alph3:        "GLP",
			numCode:      "312",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GU": {
			enName:       "Guam",
			frName:       "Guam",
			alph2:        "GU",
			alph3:        "GUM",
			numCode:      "316",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GT": {
			enName:       "Guatemala",
			frName:       "Guatemala (le)",
			alph2:        "GT",
			alph3:        "GTM",
			numCode:      "320",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GG": {
			enName:       "Guernsey",
			frName:       "Guernesey",
			alph2:        "GG",
			alph3:        "GGY",
			numCode:      "831",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GN": {
			enName:       "Guinea",
			frName:       "Guinée (la)",
			alph2:        "GN",
			alph3:        "GIN",
			numCode:      "324",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GW": {
			enName:       "Guinea-Bissau",
			frName:       "Guinée-Bissau (la)",
			alph2:        "GW",
			alph3:        "GNB",
			numCode:      "624",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GY": {
			enName:       "Guyana",
			frName:       "Guyana (le)",
			alph2:        "GY",
			alph3:        "GUY",
			numCode:      "328",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"HT": {
			enName:       "Haiti",
			frName:       "Haïti",
			alph2:        "HT",
			alph3:        "HTI",
			numCode:      "332",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"HM": {
			enName:       "Heard Island and McDonald Islands",
			frName:       "Heard-et-Îles MacDonald (l'Île)",
			alph2:        "HM",
			alph3:        "HMD",
			numCode:      "334",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"VA": {
			enName:       "Holy See (the)",
			frName:       "Saint-Siège (le)",
			alph2:        "VA",
			alph3:        "VAT",
			numCode:      "336",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"HN": {
			enName:       "Honduras",
			frName:       "Honduras (le)",
			alph2:        "HN",
			alph3:        "HND",
			numCode:      "340",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"HK": {
			enName:       "Hong Kong",
			frName:       "Hong Kong",
			alph2:        "HK",
			alph3:        "HKG",
			numCode:      "344",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"HU": {
			enName:       "Hungary",
			frName:       "Hongrie (la)",
			alph2:        "HU",
			alph3:        "HUN",
			numCode:      "348",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"IS": {
			enName:       "Iceland",
			frName:       "Islande (l')",
			alph2:        "IS",
			alph3:        "ISL",
			numCode:      "352",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"IN": {
			enName:       "India",
			frName:       "Inde (l')",
			alph2:        "IN",
			alph3:        "IND",
			numCode:      "356",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"ID": {
			enName:       "Indonesia",
			frName:       "Indonésie (l')",
			alph2:        "ID",
			alph3:        "IDN",
			numCode:      "360",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"IR": {
			enName:       "Iran (Islamic Republic of)",
			frName:       "Iran (République Islamique d')",
			alph2:        "IR",
			alph3:        "IRN",
			numCode:      "364",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"IQ": {
			enName:       "Iraq",
			frName:       "Iraq (l')",
			alph2:        "IQ",
			alph3:        "IRQ",
			numCode:      "368",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"IE": {
			enName:       "Ireland",
			frName:       "Irlande (l')",
			alph2:        "IE",
			alph3:        "IRL",
			numCode:      "372",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"IM": {
			enName:       "Isle of Man",
			frName:       "Île de Man",
			alph2:        "IM",
			alph3:        "IMN",
			numCode:      "833",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"IL": {
			enName:       "Israel",
			frName:       "Israël",
			alph2:        "IL",
			alph3:        "ISR",
			numCode:      "376",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"IT": {
			enName:       "Italy",
			frName:       "Italie (l')",
			alph2:        "IT",
			alph3:        "ITA",
			numCode:      "380",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"JM": {
			enName:       "Jamaica",
			frName:       "Jamaïque (la)",
			alph2:        "JM",
			alph3:        "JAM",
			numCode:      "388",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"JP": {
			enName:       "Japan",
			frName:       "Japon (le)",
			alph2:        "JP",
			alph3:        "JPN",
			numCode:      "392",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"JE": {
			enName:       "Jersey",
			frName:       "Jersey",
			alph2:        "JE",
			alph3:        "JEY",
			numCode:      "832",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"JO": {
			enName:       "Jordan",
			frName:       "Jordanie (la)",
			alph2:        "JO",
			alph3:        "JOR",
			numCode:      "400",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"KZ": {
			enName:       "Kazakhstan",
			frName:       "Kazakhstan (le)",
			alph2:        "KZ",
			alph3:        "KAZ",
			numCode:      "398",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"KE": {
			enName:       "Kenya",
			frName:       "Kenya (le)",
			alph2:        "KE",
			alph3:        "KEN",
			numCode:      "404",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"KI": {
			enName:       "Kiribati",
			frName:       "Kiribati",
			alph2:        "KI",
			alph3:        "KIR",
			numCode:      "296",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"KP": {
			enName:       "Korea (the Democratic People's Republic of)",
			frName:       "Corée (la République populaire démocratique de)",
			alph2:        "KP",
			alph3:        "PRK",
			numCode:      "408",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"KR": {
			enName:       "Korea (the Republic of)",
			frName:       "Corée (la République de)",
			alph2:        "KR",
			alph3:        "KOR",
			numCode:      "410",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"KW": {
			enName:       "Kuwait",
			frName:       "Koweït (le)",
			alph2:        "KW",
			alph3:        "KWT",
			numCode:      "414",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"KG": {
			enName:       "Kyrgyzstan",
			frName:       "Kirghizistan (le)",
			alph2:        "KG",
			alph3:        "KGZ",
			numCode:      "417",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"LA": {
			enName:       "Lao People's Democratic Republic (the)",
			frName:       "Lao (la République démocratique populaire)",
			alph2:        "LA",
			alph3:        "LAO",
			numCode:      "418",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"LV": {
			enName:       "Latvia",
			frName:       "Lettonie (la)",
			alph2:        "LV",
			alph3:        "LVA",
			numCode:      "428",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"LB": {
			enName:       "Lebanon",
			frName:       "Liban (le)",
			alph2:        "LB",
			alph3:        "LBN",
			numCode:      "422",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"LS": {
			enName:       "Lesotho",
			frName:       "Lesotho (le)",
			alph2:        "LS",
			alph3:        "LSO",
			numCode:      "426",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"LR": {
			enName:       "Liberia",
			frName:       "Libéria (le)",
			alph2:        "LR",
			alph3:        "LBR",
			numCode:      "430",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"LY": {
			enName:       "Libya",
			frName:       "Libye (la)",
			alph2:        "LY",
			alph3:        "LBY",
			numCode:      "434",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"LI": {
			enName:       "Liechtenstein",
			frName:       "Liechtenstein (le)",
			alph2:        "LI",
			alph3:        "LIE",
			numCode:      "438",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"LT": {
			enName:       "Lithuania",
			frName:       "Lituanie (la)",
			alph2:        "LT",
			alph3:        "LTU",
			numCode:      "440",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"LU": {
			enName:       "Luxembourg",
			frName:       "Luxembourg (le)",
			alph2:        "LU",
			alph3:        "LUX",
			numCode:      "442",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MO": {
			enName:       "Macao",
			frName:       "Macao",
			alph2:        "MO",
			alph3:        "MAC",
			numCode:      "446",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MG": {
			enName:       "Madagascar",
			frName:       "Madagascar",
			alph2:        "MG",
			alph3:        "MDG",
			numCode:      "450",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MW": {
			enName:       "Malawi",
			frName:       "Malawi (le)",
			alph2:        "MW",
			alph3:        "MWI",
			numCode:      "454",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MY": {
			enName:       "Malaysia",
			frName:       "Malaisie (la)",
			alph2:        "MY",
			alph3:        "MYS",
			numCode:      "458",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MV": {
			enName:       "Maldives",
			frName:       "Maldives (les)",
			alph2:        "MV",
			alph3:        "MDV",
			numCode:      "462",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"ML": {
			enName:       "Mali",
			frName:       "Mali (le)",
			alph2:        "ML",
			alph3:        "MLI",
			numCode:      "466",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MT": {
			enName:       "Malta",
			frName:       "Malte",
			alph2:        "MT",
			alph3:        "MLT",
			numCode:      "470",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MH": {
			enName:       "Marshall Islands (the)",
			frName:       "Marshall (les Îles)",
			alph2:        "MH",
			alph3:        "MHL",
			numCode:      "584",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MQ": {
			enName:       "Martinique",
			frName:       "Martinique (la)",
			alph2:        "MQ",
			alph3:        "MTQ",
			numCode:      "474",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MR": {
			enName:       "Mauritania",
			frName:       "Mauritanie (la)",
			alph2:        "MR",
			alph3:        "MRT",
			numCode:      "478",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MU": {
			enName:       "Mauritius",
			frName:       "Maurice",
			alph2:        "MU",
			alph3:        "MUS",
			numCode:      "480",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"YT": {
			enName:       "Mayotte",
			frName:       "Mayotte",
			alph2:        "YT",
			alph3:        "MYT",
			numCode:      "175",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MX": {
			enName:       "Mexico",
			frName:       "Mexique (le)",
			alph2:        "MX",
			alph3:        "MEX",
			numCode:      "484",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"FM": {
			enName:       "Micronesia (Federated States of)",
			frName:       "Micronésie (États fédérés de)",
			alph2:        "FM",
			alph3:        "FSM",
			numCode:      "583",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MD": {
			enName:       "Moldova (the Republic of)",
			frName:       "Moldova (la République de)",
			alph2:        "MD",
			alph3:        "MDA",
			numCode:      "498",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MC": {
			enName:       "Monaco",
			frName:       "Monaco",
			alph2:        "MC",
			alph3:        "MCO",
			numCode:      "492",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MN": {
			enName:       "Mongolia",
			frName:       "Mongolie (la)",
			alph2:        "MN",
			alph3:        "MNG",
			numCode:      "496",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"ME": {
			enName:       "Montenegro",
			frName:       "Monténégro (le)",
			alph2:        "ME",
			alph3:        "MNE",
			numCode:      "499",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MS": {
			enName:       "Montserrat",
			frName:       "Montserrat",
			alph2:        "MS",
			alph3:        "MSR",
			numCode:      "500",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MA": {
			enName:       "Morocco",
			frName:       "Maroc (le)",
			alph2:        "MA",
			alph3:        "MAR",
			numCode:      "504",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MZ": {
			enName:       "Mozambique",
			frName:       "Mozambique (le)",
			alph2:        "MZ",
			alph3:        "MOZ",
			numCode:      "508",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MM": {
			enName:       "Myanmar",
			frName:       "Myanmar (le)",
			alph2:        "MM",
			alph3:        "MMR",
			numCode:      "104",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NA": {
			enName:       "Namibia",
			frName:       "Namibie (la)",
			alph2:        "NA",
			alph3:        "NAM",
			numCode:      "516",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NR": {
			enName:       "Nauru",
			frName:       "Nauru",
			alph2:        "NR",
			alph3:        "NRU",
			numCode:      "520",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NP": {
			enName:       "Nepal",
			frName:       "Népal (le)",
			alph2:        "NP",
			alph3:        "NPL",
			numCode:      "524",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NL": {
			enName:       "Netherlands (the)",
			frName:       "Pays-Bas (les)",
			alph2:        "NL",
			alph3:        "NLD",
			numCode:      "528",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NC": {
			enName:       "New Caledonia",
			frName:       "Nouvelle-Calédonie (la)",
			alph2:        "NC",
			alph3:        "NCL",
			numCode:      "540",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NZ": {
			enName:       "New Zealand",
			frName:       "Nouvelle-Zélande (la)",
			alph2:        "NZ",
			alph3:        "NZL",
			numCode:      "554",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NI": {
			enName:       "Nicaragua",
			frName:       "Nicaragua (le)",
			alph2:        "NI",
			alph3:        "NIC",
			numCode:      "558",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NE": {
			enName:       "Niger (the)",
			frName:       "Niger (le)",
			alph2:        "NE",
			alph3:        "NER",
			numCode:      "562",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NG": {
			enName:       "Nigeria",
			frName:       "Nigéria (le)",
			alph2:        "NG",
			alph3:        "NGA",
			numCode:      "566",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NU": {
			enName:       "Niue",
			frName:       "Niue",
			alph2:        "NU",
			alph3:        "NIU",
			numCode:      "570",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NF": {
			enName:       "Norfolk Island",
			frName:       "Norfolk (l'Île)",
			alph2:        "NF",
			alph3:        "NFK",
			numCode:      "574",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MK": {
			enName:       "North Macedonia",
			frName:       "Macédoine du Nord (la)",
			alph2:        "MK",
			alph3:        "MKD",
			numCode:      "807",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MP": {
			enName:       "Northern Mariana Islands (the)",
			frName:       "Mariannes du Nord (les Îles)",
			alph2:        "MP",
			alph3:        "MNP",
			numCode:      "580",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"NO": {
			enName:       "Norway",
			frName:       "Norvège (la)",
			alph2:        "NO",
			alph3:        "NOR",
			numCode:      "578",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"OM": {
			enName:       "Oman",
			frName:       "Oman",
			alph2:        "OM",
			alph3:        "OMN",
			numCode:      "512",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PK": {
			enName:       "Pakistan",
			frName:       "Pakistan (le)",
			alph2:        "PK",
			alph3:        "PAK",
			numCode:      "586",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PW": {
			enName:       "Palau",
			frName:       "Palaos (les)",
			alph2:        "PW",
			alph3:        "PLW",
			numCode:      "585",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PS": {
			enName:       "Palestine, State of",
			frName:       "Palestine, État de",
			alph2:        "PS",
			alph3:        "PSE",
			numCode:      "275",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PA": {
			enName:       "Panama",
			frName:       "Panama (le)",
			alph2:        "PA",
			alph3:        "PAN",
			numCode:      "591",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PG": {
			enName:       "Papua New Guinea",
			frName:       "Papouasie-Nouvelle-Guinée (la)",
			alph2:        "PG",
			alph3:        "PNG",
			numCode:      "598",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PY": {
			enName:       "Paraguay",
			frName:       "Paraguay (le)",
			alph2:        "PY",
			alph3:        "PRY",
			numCode:      "600",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PE": {
			enName:       "Peru",
			frName:       "Pérou (le)",
			alph2:        "PE",
			alph3:        "PER",
			numCode:      "604",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PH": {
			enName:       "Philippines (the)",
			frName:       "Philippines (les)",
			alph2:        "PH",
			alph3:        "PHL",
			numCode:      "608",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PN": {
			enName:       "Pitcairn",
			frName:       "Pitcairn",
			alph2:        "PN",
			alph3:        "PCN",
			numCode:      "612",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PL": {
			enName:       "Poland",
			frName:       "Pologne (la)",
			alph2:        "PL",
			alph3:        "POL",
			numCode:      "616",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PT": {
			enName:       "Portugal",
			frName:       "Portugal (le)",
			alph2:        "PT",
			alph3:        "PRT",
			numCode:      "620",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PR": {
			enName:       "Puerto Rico",
			frName:       "Porto Rico",
			alph2:        "PR",
			alph3:        "PRI",
			numCode:      "630",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"QA": {
			enName:       "Qatar",
			frName:       "Qatar (le)",
			alph2:        "QA",
			alph3:        "QAT",
			numCode:      "634",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"RO": {
			enName:       "Romania",
			frName:       "Roumanie (la)",
			alph2:        "RO",
			alph3:        "ROU",
			numCode:      "642",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"RU": {
			enName:       "Russian Federation (the)",
			frName:       "Russie (la Fédération de)",
			alph2:        "RU",
			alph3:        "RUS",
			numCode:      "643",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"RW": {
			enName:       "Rwanda",
			frName:       "Rwanda (le)",
			alph2:        "RW",
			alph3:        "RWA",
			numCode:      "646",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"RE": {
			enName:       "Réunion",
			frName:       "Réunion (La)",
			alph2:        "RE",
			alph3:        "REU",
			numCode:      "638",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"BL": {
			enName:       "Saint Barthélemy",
			frName:       "Saint-Barthélemy",
			alph2:        "BL",
			alph3:        "BLM",
			numCode:      "652",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SH": {
			enName:       "Saint Helena, Ascension and Tristan da Cunha",
			frName:       "Sainte-Hélène, Ascension et Tristan da Cunha",
			alph2:        "SH",
			alph3:        "SHN",
			numCode:      "654",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"KN": {
			enName:       "Saint Kitts and Nevis",
			frName:       "Saint-Kitts-et-Nevis",
			alph2:        "KN",
			alph3:        "KNA",
			numCode:      "659",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"LC": {
			enName:       "Saint Lucia",
			frName:       "Sainte-Lucie",
			alph2:        "LC",
			alph3:        "LCA",
			numCode:      "662",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"MF": {
			enName:       "Saint Martin (French part)",
			frName:       "Saint-Martin (partie française)",
			alph2:        "MF",
			alph3:        "MAF",
			numCode:      "663",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"PM": {
			enName:       "Saint Pierre and Miquelon",
			frName:       "Saint-Pierre-et-Miquelon",
			alph2:        "PM",
			alph3:        "SPM",
			numCode:      "666",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"VC": {
			enName:       "Saint Vincent and the Grenadines",
			frName:       "Saint-Vincent-et-les Grenadines",
			alph2:        "VC",
			alph3:        "VCT",
			numCode:      "670",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"WS": {
			enName:       "Samoa",
			frName:       "Samoa (le)",
			alph2:        "WS",
			alph3:        "WSM",
			numCode:      "882",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SM": {
			enName:       "San Marino",
			frName:       "Saint-Marin",
			alph2:        "SM",
			alph3:        "SMR",
			numCode:      "674",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"ST": {
			enName:       "Sao Tome and Principe",
			frName:       "Sao Tomé-et-Principe",
			alph2:        "ST",
			alph3:        "STP",
			numCode:      "678",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SA": {
			enName:       "Saudi Arabia",
			frName:       "Arabie saoudite (l')",
			alph2:        "SA",
			alph3:        "SAU",
			numCode:      "682",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SN": {
			enName:       "Senegal",
			frName:       "Sénégal (le)",
			alph2:        "SN",
			alph3:        "SEN",
			numCode:      "686",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"RS": {
			enName:       "Serbia",
			frName:       "Serbie (la)",
			alph2:        "RS",
			alph3:        "SRB",
			numCode:      "688",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SC": {
			enName:       "Seychelles",
			frName:       "Seychelles (les)",
			alph2:        "SC",
			alph3:        "SYC",
			numCode:      "690",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SL": {
			enName:       "Sierra Leone",
			frName:       "Sierra Leone (la)",
			alph2:        "SL",
			alph3:        "SLE",
			numCode:      "694",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SG": {
			enName:       "Singapore",
			frName:       "Singapour",
			alph2:        "SG",
			alph3:        "SGP",
			numCode:      "702",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SX": {
			enName:       "Sint Maarten (Dutch part)",
			frName:       "Saint-Martin (partie néerlandaise)",
			alph2:        "SX",
			alph3:        "SXM",
			numCode:      "534",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SK": {
			enName:       "Slovakia",
			frName:       "Slovaquie (la)",
			alph2:        "SK",
			alph3:        "SVK",
			numCode:      "703",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SI": {
			enName:       "Slovenia",
			frName:       "Slovénie (la)",
			alph2:        "SI",
			alph3:        "SVN",
			numCode:      "705",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SB": {
			enName:       "Solomon Islands",
			frName:       "Salomon (les Îles)",
			alph2:        "SB",
			alph3:        "SLB",
			numCode:      "090",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SO": {
			enName:       "Somalia",
			frName:       "Somalie (la)",
			alph2:        "SO",
			alph3:        "SOM",
			numCode:      "706",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"ZA": {
			enName:       "South Africa",
			frName:       "Afrique du Sud (l')",
			alph2:        "ZA",
			alph3:        "ZAF",
			numCode:      "710",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GS": {
			enName:       "South Georgia and the South Sandwich Islands",
			frName:       "Géorgie du Sud-et-les Îles Sandwich du Sud (la)",
			alph2:        "GS",
			alph3:        "SGS",
			numCode:      "239",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SS": {
			enName:       "South Sudan",
			frName:       "Soudan du Sud (le)",
			alph2:        "SS",
			alph3:        "SSD",
			numCode:      "728",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"ES": {
			enName:       "Spain",
			frName:       "Espagne (l')",
			alph2:        "ES",
			alph3:        "ESP",
			numCode:      "724",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"LK": {
			enName:       "Sri Lanka",
			frName:       "Sri Lanka",
			alph2:        "LK",
			alph3:        "LKA",
			numCode:      "144",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SD": {
			enName:       "Sudan (the)",
			frName:       "Soudan (le)",
			alph2:        "SD",
			alph3:        "SDN",
			numCode:      "729",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SR": {
			enName:       "Suriname",
			frName:       "Suriname (le)",
			alph2:        "SR",
			alph3:        "SUR",
			numCode:      "740",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SJ": {
			enName:       "Svalbard and Jan Mayen",
			frName:       "Svalbard et l'Île Jan Mayen (le)",
			alph2:        "SJ",
			alph3:        "SJM",
			numCode:      "744",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SE": {
			enName:       "Sweden",
			frName:       "Suède (la)",
			alph2:        "SE",
			alph3:        "SWE",
			numCode:      "752",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"CH": {
			enName:       "Switzerland",
			frName:       "Suisse (la)",
			alph2:        "CH",
			alph3:        "CHE",
			numCode:      "756",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"SY": {
			enName:       "Syrian Arab Republic (the)",
			frName:       "République arabe syrienne (la)",
			alph2:        "SY",
			alph3:        "SYR",
			numCode:      "760",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TW": {
			enName:       "Taiwan (Province of China)",
			frName:       "Taïwan (Province de Chine)",
			alph2:        "TW",
			alph3:        "TWN",
			numCode:      "158",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TJ": {
			enName:       "Tajikistan",
			frName:       "Tadjikistan (le)",
			alph2:        "TJ",
			alph3:        "TJK",
			numCode:      "762",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TZ": {
			enName:       "Tanzania, the United Republic of",
			frName:       "Tanzanie (la République-Unie de)",
			alph2:        "TZ",
			alph3:        "TZA",
			numCode:      "834",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TH": {
			enName:       "Thailand",
			frName:       "Thaïlande (la)",
			alph2:        "TH",
			alph3:        "THA",
			numCode:      "764",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TL": {
			enName:       "Timor-Leste",
			frName:       "Timor-Leste (le)",
			alph2:        "TL",
			alph3:        "TLS",
			numCode:      "626",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TG": {
			enName:       "Togo",
			frName:       "Togo (le)",
			alph2:        "TG",
			alph3:        "TGO",
			numCode:      "768",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TK": {
			enName:       "Tokelau",
			frName:       "Tokelau (les)",
			alph2:        "TK",
			alph3:        "TKL",
			numCode:      "772",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TO": {
			enName:       "Tonga",
			frName:       "Tonga (les)",
			alph2:        "TO",
			alph3:        "TON",
			numCode:      "776",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TT": {
			enName:       "Trinidad and Tobago",
			frName:       "Trinité-et-Tobago (la)",
			alph2:        "TT",
			alph3:        "TTO",
			numCode:      "780",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TN": {
			enName:       "Tunisia",
			frName:       "Tunisie (la)",
			alph2:        "TN",
			alph3:        "TUN",
			numCode:      "788",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TR": {
			enName:       "Turkey",
			frName:       "Turquie (la)",
			alph2:        "TR",
			alph3:        "TUR",
			numCode:      "792",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TM": {
			enName:       "Turkmenistan",
			frName:       "Turkménistan (le)",
			alph2:        "TM",
			alph3:        "TKM",
			numCode:      "795",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TC": {
			enName:       "Turks and Caicos Islands (the)",
			frName:       "Turks-et-Caïcos (les Îles)",
			alph2:        "TC",
			alph3:        "TCA",
			numCode:      "796",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"TV": {
			enName:       "Tuvalu",
			frName:       "Tuvalu (les)",
			alph2:        "TV",
			alph3:        "TUV",
			numCode:      "798",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"UG": {
			enName:       "Uganda",
			frName:       "Ouganda (l')",
			alph2:        "UG",
			alph3:        "UGA",
			numCode:      "800",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"UA": {
			enName:       "Ukraine",
			frName:       "Ukraine (l')",
			alph2:        "UA",
			alph3:        "UKR",
			numCode:      "804",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"AE": {
			enName:       "United Arab Emirates (the)",
			frName:       "Émirats arabes unis (les)",
			alph2:        "AE",
			alph3:        "ARE",
			numCode:      "784",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"GB": {
			enName:       "United Kingdom of Great Britain and Northern Ireland (the)",
			frName:       "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)",
			alph2:        "GB",
			alph3:        "GBR",
			numCode:      "826",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"UM": {
			enName:       "United States Minor Outlying Islands (the)",
			frName:       "Îles mineures éloignées des États-Unis (les)",
			alph2:        "UM",
			alph3:        "UMI",
			numCode:      "581",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"US": {
			enName:       "United States of America (the)",
			frName:       "États-Unis d'Amérique (les)",
			alph2:        "US",
			alph3:        "USA",
			numCode:      "840",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"UY": {
			enName:       "Uruguay",
			frName:       "Uruguay (l')",
			alph2:        "UY",
			alph3:        "URY",
			numCode:      "858",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"UZ": {
			enName:       "Uzbekistan",
			frName:       "Ouzbékistan (l')",
			alph2:        "UZ",
			alph3:        "UZB",
			numCode:      "860",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"VU": {
			enName:       "Vanuatu",
			frName:       "Vanuatu (le)",
			alph2:        "VU",
			alph3:        "VUT",
			numCode:      "548",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"VE": {
			enName:       "Venezuela (Bolivarian Republic of)",
			frName:       "Venezuela (République bolivarienne du)",
			alph2:        "VE",
			alph3:        "VEN",
			numCode:      "862",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"VN": {
			enName:       "Viet Nam",
			frName:       "Viet Nam (le)",
			alph2:        "VN",
			alph3:        "VNM",
			numCode:      "704",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"VG": {
			enName:       "Virgin Islands (British)",
			frName:       "Vierges britanniques (les Îles)",
			alph2:        "VG",
			alph3:        "VGB",
			numCode:      "092",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"VI": {
			enName:       "Virgin Islands (U.S.)",
			frName:       "Vierges des États-Unis (les Îles)",
			alph2:        "VI",
			alph3:        "VIR",
			numCode:      "850",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"WF": {
			enName:       "Wallis and Futuna",
			frName:       "Wallis-et-Futuna",
			alph2:        "WF",
			alph3:        "WLF",
			numCode:      "876",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"EH": {
			enName:       "Western Sahara*",
			frName:       "Sahara occidental (le)*",
			alph2:        "EH",
			alph3:        "ESH",
			numCode:      "732",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"YE": {
			enName:       "Yemen",
			frName:       "Yémen (le)",
			alph2:        "YE",
			alph3:        "YEM",
			numCode:      "887",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"ZM": {
			enName:       "Zambia",
			frName:       "Zambie (la)",
			alph2:        "ZM",
			alph3:        "ZMB",
			numCode:      "894",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"ZW": {
			enName:       "Zimbabwe",
			frName:       "Zimbabwe (le)",
			alph2:        "ZW",
			alph3:        "ZWE",
			numCode:      "716",
			official:     true,
			active:       true,
			description:  "Official ISO Code",
			organisation: "ISO",
		},
		"X5": {
			enName:       "stateless",
			frName:       "stateless",
			alph2:        "X5",
			alph3:        "XX5",
			numCode:      "XX5",
			official:     false,
			active:       true,
			description:  "code used to describe stateless entities in country-by-country reporting",
			organisation: "OECD",
		},
	}
)
